10_homework_store_with_amount
golovnevs/redi_js_spring_2020 pull request #12
Opened 2020-05-07 01:16 UTC by golovnevs

Hello teachers! Here is my homework for lesson 10(conditions) - online store with amount.

2020-05-09 21:00 UTC, MrTim requested changes
Nice works! Left some comments regarding the structuring

2020-05-09 21:00 UTC, MrTim commented on 10_homework_store_amount/online_store.css
> +
empty line

2020-05-09 21:00 UTC, MrTim commented on 10_homework_store_amount/online_store.css
> +
2 empty lines

2020-05-09 21:00 UTC, MrTim commented on 10_homework_store_amount/script.js
> +        if (bikes[i].amount > 1 && bikes[i].amount <= 3) {
you can structure this code a bit better:
```js
if (bikes[i].amount > 1 && bikes[i].amount <= 3) {
  bikeCard.innerHTML = ` 
    <h2>${bikes[i].brand} ${bikes[i].model}</h2>
    <img class="bikePic" id="pic_${i}" src="${bikes[i].imgSrc}" />
    <li>Price: ${bikes[i].price} ${bikes[i].currency}</li>
    <li>Year: ${bikes[i].condition.year}</li>
    <li>Mileage: ${bikes[i].condition.mileage} ${bikes[i].condition.mileageUnit}</li>
    <li>Colour: ${bikes[i].colour}</li>
    <li>Engine: ${bikes[i].engineCapacity} cc</li>
    <p>${bikes[i].description}</p>
    <li id="${i}">Avaliable now: ${bikes[i].amount} (almost out of stock)</li>
  `;
} else if (...) {
  ...
} else {
  ...
}
```

2020-05-09 21:00 UTC, MrTim commented on 10_homework_store_amount/script.js
> +        if (bikes[i].amount ==0){
spaces around `=` and please adjust the structure of if-else for regardign comment above

2020-05-09 21:00 UTC, MrTim commented on 10_homework_store_amount/script.js
> +                bikes[i].amount = bikes[i].amount-1;
you can do the following in 2 other ways: `amount -= 1` or `amount = --amount`

2020-05-09 22:21 UTC, golovnevs commented on 10_homework_store_amount/online_store.css
> +
Fixed.

2020-05-09 22:22 UTC, golovnevs commented on 10_homework_store_amount/online_store.css
> +
That's experimental part of code, i dorgot to delete it. I will be more attentive. Thank you!   Fixed.

2020-05-09 22:27 UTC, golovnevs commented on 10_homework_store_amount/script.js
> +        if (bikes[i].amount ==0){
Fixed.

2020-05-09 22:28 UTC, golovnevs commented on 10_homework_store_amount/script.js
> +                bikes[i].amount = bikes[i].amount-1;
Fixed, thank you!

2020-05-09 22:34 UTC, golovnevs commented on 10_homework_store_amount/script.js
> +        if (bikes[i].amount > 1 && bikes[i].amount <= 3) {
Fixed and remembered.

2020-05-10 08:35 UTC, MrTim approved these changes
All good now! I have one suggestion to improve:
In bikeListDisplay function you have a lot of duplication in your if-else statement, this structure
```js
  bikeCard.innerHTML = ` 
    <h2>${bikes[i].brand} ${bikes[i].model}</h2>
    <img class="bikePic" id="pic_${i}" src="${bikes[i].imgSrc}" />
    <li>Price: ${bikes[i].price} ${bikes[i].currency}</li>
    <li>Year: ${bikes[i].condition.year}</li>
    <li>Mileage: ${bikes[i].condition.mileage} ${bikes[i].condition.mileageUnit}</li>
    <li>Colour: ${bikes[i].colour}</li>
    <li>Engine: ${bikes[i].engineCapacity} cc</li>
    <p>${bikes[i].description}</p>
    <li id="${i}">Avaliable now: ${bikes[i].amount} (almost out of stock)</li>
`;
```
is almost the same with only one difference - the last sentence inside li tag. You can create a function for ex. getCardLayout with two parameters: data - your bike data and last sentence. So the idea would be to have something like: 
```js
  const availability = Avaliable now: ${bikes[i].amount} (almost out of stock) // or other sentence depends on available amount
  bikeCard.innerHTML = getCardLayout(bikes[i], availability);
```
This would simplify your code.

But if you don't want to do it you can skip it and just merge as it is.

2020-05-18 20:43 UTC, merged